baseURL = "https://lifematrix.github.io/"
languageCode = "en-us"
title = "LifeMatrix"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  description = "Compilers 路 Cryptography 路 Scientific Computing"

  [params.profileMode]
    enabled = true
    title = "LifeMatrix"
    subtitle = "Compilers 路 Cryptography 路 Scientific Computing"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
